version: '2'

networks:
  db-conn:
    driver: bridge

services:
  mysql:
    build: ./db
    container_name: piccolo-mysql
    environment:
      - MYSQL_DATABASE=edogawa01
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
    ports: 
      - "3306:3306"
    networks:
      - db-conn
    volumes:
      - ./db/data:/var/lib/mysql
  
  backend:
    build: ./backend
    container_name: piccolo-backend
    depends_on:
      - mysql
    environment:
      - ENV_MODE=development
    ports:
      - "8001:8001"
    volumes:
      - ./backend/files:/app
      - /app/node_modules
    networks:
      - db-conn
    entrypoint: "npm start"
  
  frontend:
    build: ./frontend
    container_name: piccolo-frontend
    depends_on:
      - backend
    environment:
      - ENV_MODE=development 
    ports:
      - "8002:8002"
    networks:
      - db-conn
    volumes:
      - ./frontend/files:/app
      - /app/node_modules
    entrypoint: "npm run dev"

