from node:12.1.0
maintainer eunkoo lee
run mkdir -p /app
workdir /app
copy ./files/package.json /app/
run npm install  --no-optional
#run npm audit fix  --no-optional
expose 8001 80
#cmd ["npm","start"]

